services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: employee_point_system
      DB_USERNAME: root
      DB_PASSWORD: secret
      MAIL_HOST: mailhog
      MAIL_PORT: 1025

  vite:
    image: node:18.16.0
    container_name: employee-vite
    working_dir: /var/www/html
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - app


  mysql:
    image: mysql:8.0.41
    container_name: employee-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: employee_point_system
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: employee-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data:
